// ============================================================================
// DEVELOPMENT-ONLY FASHION FEED DATASET
// ============================================================================
// This file provides 40 visually varied outfit entries for frontend
// development and visual testing. It is NOT used in production.
//
// Rules:
// - All IDs are negative (-1 through -40) to never collide with real data
// - Every entry has ONE main image (Unsplash fashion photography)
// - Every image ID is UNIQUE (verified to return 200 OK)
// - Entries are outfit/model focused: full-body looks, editorial styling,
//   streetwear, old money, Korean casual, Y2K, college, oversized, formal
// - `ratio` drives varied pin heights in the masonry feed (2/3, 3/4, 4/5, 5/8)
// - No duplicate image spam, no product close-ups
//
// To remove: delete this file and remove the fallback import in App.jsx
//
// NOTE: The model working on this project cannot view images, so every URL
// below was validated for existence via HTTP 200 status checks rather than
// visual inspection.
// ============================================================================

const img = (photoId, width = 480) =>
  `https://images.unsplash.com/${photoId}?auto=format&fit=crop&w=${width}&q=80`

const demoFashionFeed = [
  {
    id: -1,
    title: 'Off-Duty Urban Layers',
    category: 'Streetwear',
    imageUrl: img('photo-1529139574466-a303027c1d8b'),
    description: 'Layered streetwear with an easy oversized silhouette.',
    tags: ['streetwear', 'layering', 'urban'],
    ratio: '2/3',
  },
  {
    id: -2,
    title: 'Boardroom Ready',
    category: 'Formal',
    imageUrl: img('photo-1617137968427-85924c800a22'),
    description: 'Sharp tailored suiting in a classic cut.',
    tags: ['formal', 'tailoring', 'classic'],
    ratio: '3/4',
  },
  {
    id: -3,
    title: 'Camel Coat Edit',
    category: 'Old Money',
    imageUrl: img('photo-1515886657613-9f3515b0c78f'),
    description: 'Quiet-luxury neutrals anchored by a long camel coat.',
    tags: ['old-money', 'camel', 'coat'],
    ratio: '2/3',
  },
  {
    id: -4,
    title: 'Summer Whites',
    category: 'Summer',
    imageUrl: img('photo-1490481651871-ab68de25d43d'),
    description: 'Head-to-toe white for long sunny days.',
    tags: ['summer', 'white', 'light'],
    ratio: '3/4',
  },
  {
    id: -5,
    title: 'Denim Jacket Layer',
    category: 'Streetwear',
    imageUrl: img('photo-1552374196-1ab2a1c593e8'),
    description: 'Layered denim with a relaxed street stance.',
    tags: ['streetwear', 'denim', 'casual'],
    ratio: '2/3',
  },
  {
    id: -6,
    title: 'Campus Tote Look',
    category: 'College',
    imageUrl: img('photo-1523381210434-271e8be1f52b'),
    description: 'Easy campus styling, finished with a tote.',
    tags: ['college', 'campus', 'casual'],
    ratio: '4/5',
  },
  {
    id: -7,
    title: 'Everyday Neutrals',
    category: 'Casual',
    imageUrl: img('photo-1506629082955-511b1aa562c8'),
    description: 'Simple tonal layers that just work.',
    tags: ['casual', 'neutral', 'everyday'],
    ratio: '2/3',
  },
  {
    id: -8,
    title: 'Seoul Street Minimal',
    category: 'Korean',
    imageUrl: img('photo-1496747611176-843222e1e57c'),
    description: 'Clean Seoul-inspired minimal from head to toe.',
    tags: ['korean', 'minimal', 'street'],
    ratio: '3/4',
  },
  {
    id: -9,
    title: 'Neon District Fit',
    category: 'Streetwear',
    imageUrl: img('photo-1554568218-0f1715e72254'),
    description: 'Nighttime streetwear with muted neon accents.',
    tags: ['streetwear', 'night', 'urban'],
    ratio: '5/8',
  },
  {
    id: -10,
    title: 'Heritage Golf Day',
    category: 'Old Money',
    imageUrl: img('photo-1488161628813-04466f872be2'),
    description: 'Classic preppy golf look with old-school charm.',
    tags: ['old-money', 'preppy', 'classic'],
    ratio: '3/4',
  },
  {
    id: -11,
    title: 'Studio Portrait Fit',
    category: 'Formal',
    imageUrl: img('photo-1495385794356-15371f348c31'),
    description: 'Editorial tailoring with a soft-shoulder cut.',
    tags: ['formal', 'editorial', 'tailoring'],
    ratio: '2/3',
  },
  {
    id: -12,
    title: 'Off-Duty City Look',
    category: 'Streetwear',
    imageUrl: img('photo-1503342217505-b0a15ec3261c'),
    description: 'City-ready casual with relaxed proportions.',
    tags: ['streetwear', 'city', 'casual'],
    ratio: '4/5',
  },
  {
    id: -13,
    title: 'Retro Shades Fit',
    category: 'Y2K',
    imageUrl: img('photo-1469334031218-e382a71b716b'),
    description: 'Y2K energy with tinted shades and sharp lines.',
    tags: ['y2k', 'retro', 'shades'],
    ratio: '3/4',
  },
  {
    id: -14,
    title: 'Street Easy',
    category: 'Casual',
    imageUrl: img('photo-1520975954732-35dd22299614'),
    description: 'Understated street styling, zero effort.',
    tags: ['casual', 'street', 'everyday'],
    ratio: '2/3',
  },
  {
    id: -15,
    title: 'Window Shopping Edit',
    category: 'Summer',
    imageUrl: img('photo-1445205170230-053b83016050'),
    description: 'Bright summer street style for slow city days.',
    tags: ['summer', 'street', 'bright'],
    ratio: '3/4',
  },
  {
    id: -16,
    title: 'Yellow Drama',
    category: 'Y2K',
    imageUrl: img('photo-1490114538077-0a7f8cb49891'),
    description: 'Bold color-blocking straight from the early 2000s.',
    tags: ['y2k', 'color', 'bold'],
    ratio: '5/8',
  },
  {
    id: -17,
    title: 'Study Break Layer',
    category: 'College',
    imageUrl: img('photo-1543087903-1ac2ec7aa8c5'),
    description: 'Campus layering for long days on the quad.',
    tags: ['college', 'layering', 'casual'],
    ratio: '4/5',
  },
  {
    id: -18,
    title: 'Archive Portrait',
    category: 'Vintage',
    imageUrl: img('photo-1534528741775-53994a69daeb'),
    description: 'Vintage-flavored styling with an editorial mood.',
    tags: ['vintage', 'editorial', 'retro'],
    ratio: '3/4',
  },
  {
    id: -19,
    title: 'Weekend Layered',
    category: 'Casual',
    imageUrl: img('photo-1502716119720-b23a93e5fe1b'),
    description: 'Weekend-easy layers with a relaxed finish.',
    tags: ['casual', 'weekend', 'layering'],
    ratio: '2/3',
  },
  {
    id: -20,
    title: 'Studio White',
    category: 'Minimal',
    imageUrl: img('photo-1524504388940-b1c1722653e1'),
    description: 'Crisp whites and clean lines, quietly done.',
    tags: ['minimal', 'white', 'clean'],
    ratio: '3/4',
  },
  {
    id: -21,
    title: 'City Stroll',
    category: 'Casual',
    imageUrl: img('photo-1503342394128-c104d54dba01'),
    description: 'Easygoing city wear with all-day comfort.',
    tags: ['casual', 'city', 'comfort'],
    ratio: '2/3',
  },
  {
    id: -22,
    title: 'Sharp Shoulder Suit',
    category: 'Formal',
    imageUrl: img('photo-1500648767791-00dcc994a43e'),
    description: 'A precise suit for meetings that matter.',
    tags: ['formal', 'suit', 'sharp'],
    ratio: '3/4',
  },
  {
    id: -23,
    title: 'Coastline Light',
    category: 'Summer',
    imageUrl: img('photo-1509233725247-49e657c54213'),
    description: 'Breathable summer layers built for the coast.',
    tags: ['summer', 'light', 'coastal'],
    ratio: '4/5',
  },
  {
    id: -24,
    title: 'Winter Overcoat',
    category: 'Winter',
    imageUrl: img('photo-1485738422979-f5c462d49f74'),
    description: 'Long overcoat layers for serious cold.',
    tags: ['winter', 'overcoat', 'layering'],
    ratio: '2/3',
  },
  {
    id: -25,
    title: 'Sunday Knit',
    category: 'Winter',
    imageUrl: img('photo-1521510895919-46920266ddb3'),
    description: 'Easy knitwear for slow winter weekends.',
    tags: ['winter', 'knit', 'cozy'],
    ratio: '4/5',
  },
  {
    id: -26,
    title: 'Night Parka Fit',
    category: 'Winter',
    imageUrl: img('photo-1503341504253-dff4815485f1'),
    description: 'Street-ready winter layers under a parka.',
    tags: ['winter', 'streetwear', 'parka'],
    ratio: '2/3',
  },
  {
    id: -27,
    title: 'All-Black Uniform',
    category: 'Monochrome',
    imageUrl: img('photo-1512418490979-92798cec1380'),
    description: 'Monochrome dressing in a single shade.',
    tags: ['monochrome', 'black', 'uniform'],
    ratio: '5/8',
  },
  {
    id: -28,
    title: 'Oversized Knit Fit',
    category: 'Oversized',
    imageUrl: img('photo-1544441893-675973e31985'),
    description: 'Volume on volume with a cozy knit outline.',
    tags: ['oversized', 'knit', 'relaxed'],
    ratio: '2/3',
  },
  {
    id: -29,
    title: 'Relaxed Suiting',
    category: 'Formal',
    imageUrl: img('photo-1507679799987-c73779587ccf'),
    description: 'Unstructured tailoring worn easy.',
    tags: ['formal', 'smart-casual', 'relaxed'],
    ratio: '3/4',
  },
  {
    id: -30,
    title: 'Seoul Street Dress',
    category: 'Korean',
    imageUrl: img('photo-1509631179647-0177331693ae'),
    description: 'Effortless Seoul styling with a clean silhouette.',
    tags: ['korean', 'seoul', 'street'],
    ratio: '5/8',
  },
  {
    id: -31,
    title: 'Quiet Luxury Layer',
    category: 'Old Money',
    imageUrl: img('photo-1617137984095-74e4e5e3613f'),
    description: 'Understated luxury in muted earth tones.',
    tags: ['old-money', 'quiet-luxury', 'earthy'],
    ratio: '3/4',
  },
  {
    id: -32,
    title: 'Beige Proportions',
    category: 'Casual',
    imageUrl: img('photo-1509316975850-ff9c5deb0cd9'),
    description: 'Soft beige tones with considered proportions.',
    tags: ['casual', 'beige', 'proportions'],
    ratio: '4/5',
  },
  {
    id: -33,
    title: 'Black Coat Walk',
    category: 'Monochrome',
    imageUrl: img('photo-1509941943102-10c232535736'),
    description: 'Sweeping black coat, confident stride.',
    tags: ['monochrome', 'coat', 'walk'],
    ratio: '2/3',
  },
  {
    id: -34,
    title: 'Coat Statement',
    category: 'Old Money',
    imageUrl: img('photo-1434389677669-e08b4cac3105'),
    description: 'A statement coat doing the talking.',
    tags: ['old-money', 'coat', 'statement'],
    ratio: '2/3',
  },
  {
    id: -35,
    title: 'All-White Minimal',
    category: 'Minimal',
    imageUrl: img('photo-1572804013309-59a88b7e92f1'),
    description: 'Pared-back white styling, nothing extra.',
    tags: ['minimal', 'white', 'clean'],
    ratio: '3/4',
  },
  {
    id: -36,
    title: 'Linen Afternoon',
    category: 'Summer',
    imageUrl: img('photo-1590874103328-eac38a683ce7'),
    description: 'Airy linen for warm afternoons.',
    tags: ['summer', 'linen', 'light'],
    ratio: '4/5',
  },
  {
    id: -37,
    title: 'Morning Commute',
    category: 'Casual',
    imageUrl: img('photo-1490578474895-699cd4e2cf59'),
    description: 'Easy smart-casual for the daily commute.',
    tags: ['casual', 'commute', 'smart'],
    ratio: '2/3',
  },
  {
    id: -38,
    title: 'Market Run Fit',
    category: 'Casual',
    imageUrl: img('photo-1483985988355-763728e1935b'),
    description: 'Street-style comfort for getting things done.',
    tags: ['casual', 'street', 'everyday'],
    ratio: '4/5',
  },
  {
    id: -39,
    title: 'Puffer Oversize',
    category: 'Oversized',
    imageUrl: img('photo-1617127365659-c47fa864d8bc'),
    description: 'Padded oversize volume at streetwear scale.',
    tags: ['oversized', 'streetwear', 'puffer'],
    ratio: '5/8',
  },
  {
    id: -40,
    title: 'Navy Suiting',
    category: 'Formal',
    imageUrl: img('photo-1560250097-0b93528c311a'),
    description: 'Deep navy suiting for after-hours.',
    tags: ['formal', 'navy', 'evening'],
    ratio: '3/4',
  },
]

export default demoFashionFeed