// ============================================================================
// DEVELOPMENT-ONLY FASHION FEED DATASET
// ============================================================================
// This file provides 40 visually varied fashion entries for frontend
// development and visual testing. It is NOT used in production.
//
// Rules:
// - All IDs are negative (-1 through -40) to never collide with real data
// - Every entry has ONE main image (Unsplash fashion photography)
// - Multiple aspect ratios, categories, and visual compositions
// - No duplicate image spam
// - All content is fashion-related
//
// To remove: delete this file and remove the fallback import in FeedPage.jsx
// ============================================================================

const demoFashionFeed = [
  {
    id: -1,
    title: 'Minimal Streetwear Layers',
    category: 'Streetwear',
    imageUrl: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=480&q=80',
    description: 'Clean layered streetwear with oversized proportions.',
    tags: ['streetwear', 'layering', 'minimal'],
    products: [],
    variant: 'standard',
  },
  {
    id: -2,
    title: 'Old Money Elegance',
    category: 'Old Money',
    imageUrl: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=480&q=80',
    description: 'Timeless refined style with classic tailoring.',
    tags: ['old-money', 'classic', 'tailoring'],
    products: [],
    variant: 'editorial',
  },
  {
    id: -3,
    title: 'Korean Street Style',
    category: 'Korean',
    imageUrl: 'https://images.unsplash.com/photo-1539109136881-3be0616ffa4a?auto=format&fit=crop&w=480&q=80',
    description: 'Effortless Korean casual with relaxed silhouettes.',
    tags: ['korean', 'casual', 'street-style'],
    products: [],
    variant: 'standard',
  },
  {
    id: -4,
    title: 'Urban Monochrome',
    category: 'Monochrome',
    imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=480&q=80',
    description: 'All-black urban aesthetic with clean lines.',
    tags: ['monochrome', 'urban', 'minimal'],
    products: [],
    variant: 'minimal',
  },
  {
    id: -5,
    title: 'Summer Whites',
    category: 'Summer',
    imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=480&q=80',
    description: 'Breathable summer whites for warm days.',
    tags: ['summer', 'minimal', 'whites'],
    products: [],
    variant: 'trend',
  },
  {
    id: -6,
    title: 'Oversized Denim Game',
    category: 'Denim',
    imageUrl: 'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?auto=format&fit=crop&w=480&q=80',
    description: 'Oversized denim jacket paired with relaxed fits.',
    tags: ['denim', 'oversized', 'casual'],
    products: [],
    variant: 'shoppable',
  },
  {
    id: -7,
    title: 'Campus Ready',
    category: 'College',
    imageUrl: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=480&q=80',
    description: 'Preppy campus style with modern edge.',
    tags: ['college', 'preppy', 'campus'],
    products: [],
    variant: 'standard',
  },
  {
    id: -8,
    title: 'Vintage Grain',
    category: 'Vintage',
    imageUrl: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=480&q=80',
    description: 'Retro-inspired outfit with vintage textures.',
    tags: ['vintage', 'retro', 'grain'],
    products: [],
    variant: 'editorial',
  },
  {
    id: -9,
    title: 'Y2K Flash',
    category: 'Y2K',
    imageUrl: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=480&q=80',
    description: 'Y2K-inspired metallic and glossy elements.',
    tags: ['y2k', 'futuristic', 'glossy'],
    products: [],
    variant: 'trend',
  },
  {
    id: -10,
    title: 'Minimal Studio',
    category: 'Minimal',
    imageUrl: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=480&q=80',
    description: 'Studio-lit minimal fashion with clean composition.',
    tags: ['minimal', 'studio', 'clean'],
    products: [],
    variant: 'minimal',
  },
  {
    id: -11,
    title: 'Winter Layering',
    category: 'Winter',
    imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=480&q=80',
    description: 'Smart winter layering with textures and depth.',
    tags: ['winter', 'layering', 'textures'],
    products: [],
    variant: 'standard',
  },
  {
    id: -12,
    title: 'Casual Friday Fit',
    category: 'Casual',
    imageUrl: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=480&q=80',
    description: 'Relaxed casual outfit for everyday comfort.',
    tags: ['casual', 'comfort', 'everyday'],
    products: [],
    variant: 'standard',
  },
  {
    id: -13,
    title: 'Formal Edge',
    category: 'Formal',
    imageUrl: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=480&q=80',
    description: 'Modern formal with sharp tailoring.',
    tags: ['formal', 'tailoring', 'sharp'],
    products: [],
    variant: 'editorial',
  },
  {
    id: -14,
    title: 'Street Sneakers',
    category: 'Streetwear',
    imageUrl: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?auto=format&fit=crop&w=480&q=80',
    description: 'Sneaker-focused streetwear composition.',
    tags: ['streetwear', 'sneakers', 'close-up'],
    products: [],
    variant: 'shoppable',
  },
  {
    id: -15,
    title: 'Seated Style',
    category: 'Casual',
    imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=480&q=80',
    description: 'Effortless seated pose with layered casual wear.',
    tags: ['casual', 'seated', 'relaxed'],
    products: [],
    variant: 'standard',
  },
  {
    id: -16,
    title: 'Accessories Edit',
    category: 'Minimal',
    imageUrl: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=480&q=80',
    description: 'Curated accessories for a polished look.',
    tags: ['accessories', 'minimal', 'curated'],
    products: [],
    variant: 'shoppable',
  },
  {
    id: -17,
    title: 'Night Streetwear',
    category: 'Streetwear',
    imageUrl: 'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?auto=format&fit=crop&w=480&q=80',
    description: 'Nighttime urban streetwear with moody lighting.',
    tags: ['streetwear', 'night', 'urban'],
    products: [],
    variant: 'editorial',
  },
  {
    id: -18,
    title: 'Mirror Outfit Check',
    category: 'Korean',
    imageUrl: 'https://images.unsplash.com/photo-1539109136881-3be0616ffa4a?auto=format&fit=crop&w=480&q=80',
    description: 'Mirror selfie style with Korean fashion influence.',
    tags: ['korean', 'mirror', 'selfie'],
    products: [],
    variant: 'standard',
  },
  {
    id: -19,
    title: 'Cafe Aesthetic',
    category: 'Vintage',
    imageUrl: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=480&q=80',
    description: 'Warm cafe setting with vintage-inspired outfit.',
    tags: ['vintage', 'cafe', 'aesthetic'],
    products: [],
    variant: 'editorial',
  },
  {
    id: -20,
    title: 'Denim Detail',
    category: 'Denim',
    imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=480&q=80',
    description: 'Close-up denim texture and stitching detail.',
    tags: ['denim', 'detail', 'texture'],
    products: [],
    variant: 'minimal',
  },
  {
    id: -21,
    title: 'Rooftop Fashion',
    category: 'Casual',
    imageUrl: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=480&q=80',
    description: 'Rooftop golden hour with casual fashion.',
    tags: ['casual', 'rooftop', 'golden-hour'],
    products: [],
    variant: 'standard',
  },
  {
    id: -22,
    title: 'Bag Styling',
    category: 'Minimal',
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=480&q=80',
    description: 'Statement bag as the focal point of the outfit.',
    tags: ['bag', 'accessories', 'styling'],
    products: [],
    variant: 'shoppable',
  },
  {
    id: -23,
    title: 'Editorial Portrait',
    category: 'Old Money',
    imageUrl: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=480&q=80',
    description: 'Fashion editorial portrait with classic styling.',
    tags: ['editorial', 'portrait', 'classic'],
    products: [],
    variant: 'editorial',
  },
  {
    id: -24,
    title: 'Side Profile Fit',
    category: 'Streetwear',
    imageUrl: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=480&q=80',
    description: 'Side profile showcasing streetwear silhouette.',
    tags: ['streetwear', 'profile', 'silhouette'],
    products: [],
    variant: 'standard',
  },
  {
    id: -25,
    title: 'Watch Detail',
    category: 'Formal',
    imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=480&q=80',
    description: 'Wristwatch as the statement accessory.',
    tags: ['watch', 'accessories', 'detail'],
    products: [],
    variant: 'minimal',
  },
  {
    id: -26,
    title: 'Trending Now',
    category: 'Trending',
    imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=480&q=80',
    description: 'This week most saved outfit on StylePin.',
    tags: ['trending', 'popular', 'saved'],
    products: [],
    variant: 'trend',
  },
  {
    id: -27,
    title: 'Layering Detail',
    category: 'Winter',
    imageUrl: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=480&q=80',
    description: 'Close-up of winter layering techniques.',
    tags: ['layering', 'winter', 'detail'],
    products: [],
    variant: 'minimal',
  },
  {
    id: -28,
    title: 'Korean Casual Layers',
    category: 'Korean',
    imageUrl: 'https://images.unsplash.com/photo-1539109136881-3be0616ffa4a?auto=format&fit=crop&w=480&q=80',
    description: 'Relaxed Korean casual with thoughtful layering.',
    tags: ['korean', 'casual', 'layers'],
    products: [],
    variant: 'standard',
  },
  {
    id: -29,
    title: 'Glasses Styling',
    category: 'Minimal',
    imageUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=480&q=80',
    description: 'Eyewear as a style statement.',
    tags: ['glasses', 'accessories', 'styling'],
    products: [],
    variant: 'shoppable',
  },
  {
    id: -30,
    title: 'College Campus Walk',
    category: 'College',
    imageUrl: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=480&q=80',
    description: 'Walking across campus in preppy layered style.',
    tags: ['college', 'campus', 'walking'],
    products: [],
    variant: 'standard',
  },
  {
    id: -31,
    title: 'Monochrome Power',
    category: 'Monochrome',
    imageUrl: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=480&q=80',
    description: 'Power monochrome with tonal dressing.',
    tags: ['monochrome', 'power', 'tonal'],
    products: [],
    variant: 'editorial',
  },
  {
    id: -32,
    title: 'Y2K Nostalgia',
    category: 'Y2K',
    imageUrl: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=480&q=80',
    description: 'Nostalgic Y2K elements with modern styling.',
    tags: ['y2k', 'nostalgia', 'retro'],
    products: [],
    variant: 'trend',
  },
  {
    id: -33,
    title: 'Sneaker Close-Up',
    category: 'Streetwear',
    imageUrl: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?auto=format&fit=crop&w=480&q=80',
    description: 'Detailed sneaker shot with outfit context.',
    tags: ['sneakers', 'close-up', 'streetwear'],
    products: [],
    variant: 'minimal',
  },
  {
    id: -34,
    title: 'Summer Breeze',
    category: 'Summer',
    imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=480&q=80',
    description: 'Light and airy summer fashion moment.',
    tags: ['summer', 'breeze', 'light'],
    products: [],
    variant: 'standard',
  },
  {
    id: -35,
    title: 'Fabric Texture',
    category: 'Minimal',
    imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=480&q=80',
    description: 'Close-up of premium fabric texture and weave.',
    tags: ['fabric', 'texture', 'detail'],
    products: [],
    variant: 'minimal',
  },
  {
    id: -36,
    title: 'Streetwise',
    category: 'Streetwear',
    imageUrl: 'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?auto=format&fit=crop&w=480&q=80',
    description: 'Confident streetwear with urban backdrop.',
    tags: ['streetwear', 'urban', 'confident'],
    products: [],
    variant: 'standard',
  },
  {
    id: -37,
    title: 'Oversized silhouette',
    category: 'Oversized',
    imageUrl: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=480&q=80',
    description: 'Playing with oversized proportions and drape.',
    tags: ['oversized', 'proportions', 'drape'],
    products: [],
    variant: 'editorial',
  },
  {
    id: -38,
    title: 'Casual Weekend',
    category: 'Casual',
    imageUrl: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=480&q=80',
    description: 'Laid-back weekend outfit for errands and brunch.',
    tags: ['casual', 'weekend', 'relaxed'],
    products: [],
    variant: 'standard',
  },
  {
    id: -39,
    title: 'Vintage Moments',
    category: 'Vintage',
    imageUrl: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=480&q=80',
    description: 'Captured moment with vintage film grain.',
    tags: ['vintage', 'grain', 'moment'],
    products: [],
    variant: 'editorial',
  },
  {
    id: -40,
    title: 'New Drops Alert',
    category: 'Trending',
    imageUrl: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=480&q=80',
    description: 'Fresh arrivals just landed on the feed.',
    tags: ['trending', 'new', 'drops'],
    products: [],
    variant: 'trend',
  },
]

export default demoFashionFeed
